=== amardeep247/XMLDemo/XMLDemo/employee.xsd
<?xml version="1.0"?>
<!--
Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
Click nbfs://nbhost/SystemFileSystem/Templates/XML/XmlSchema.xsd to edit this template
-->

<xs:schema version="1.0"
           xmlns:xs="http://www.w3.org/2001/XMLSchema"
           elementFormDefault="qualified">
    <!-- Define complex type for the employee element -->
    <xs:element name="employee">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="name" type="xs:string"/>
                <xs:element name="age" type="xs:integer"/>
                <xs:element name="department" type="xs:string"/>
                <xs:element name="salary" type="xs:decimal"/>
            </xs:sequence>
            <xs:attribute name="id" type="xs:string"/>
        </xs:complexType>
    </xs:element>

    <!-- Define complex type for the company element -->
    <xs:element name="company">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="employee" minOccurs="0" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== amardeep247/XMLDemo/XMLDemo/src/main/webapp/employees.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
Click nbfs://nbhost/SystemFileSystem/Templates/XML/XMLDocument.xml to edit this template
-->



<company
    xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
    xsi:noNamespaceSchemaLocation='employee.xsd'>
    <employee id="1">
        <name>John</name>
        <age>25</age>
        <department>Accounting</department>
        <salary>50000</salary>
    </employee>
    <employee id="2">
       <name>Harry</name>
        <age>25</age>
        <department>Finance</department>
        <salary>4000</salary>
    </employee>
  

</company>
